version: "2"

services:
  mongodb:
    image: mongo:latest
    command: --smallfiles
    ports:
      - "27017:27017"

  mongo-seed:
    build: ./mongo-seed
    depends_on:
      - mongodb

  intro-ui:
    image: blockcerts/certintro_web:1.0
    ports:
      - "5001:5001"

  web:
    build: .
    env_file:
      - ./cert-viewer-local.env
    command: python -u /cert-viewer/run.py
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
      - mongo-seed
      - intro-ui




