site_name: cert-viewer

pages:
- Home: index.md
- Quick Start: quick_start.md
- Installation: installation.md
- Configuration: configuration.md
- Testing: testing.md
- Certificate Format: CERTIFICATE.md
- Database Collections: database_collections.md
- Verify a Certificate: verify.md

theme: readthedocs



